### ISSUE TITLE
Lost NY Times credentials

### ISSUE THREAD

**Issue by irontechmonkey** [kebernet/shortyz#78]
I've twice seen the NY Times credential become erased during an update. This may occur during an update between specific versions but I was unable to pin it down. 

This occured on my primary device a few days ago and was rectified by restoring an older version from TiBU and updating via Play Store again. On that device I had been updating Shortyz at each release posted to Playstore.

The second time was on a secondary device just moments ago when I was testing this different issue https://github.com/kebernet/shortyz/issues/77. I was skipping more Shorty'z versions between updates in this case.

Also, I hope you dont mind my slipping in this slightly off topic question. What causes the text of puzzles in the list to be red. I noticed this while testing on the secondary device which had not been updated in a few months, and it was fixed by app cache/data clear - uninstall - install, so I assume it has something to do with the age or other status of the puzzles. If there there is a batter place for this sort of question  please do direct me there.

**Comment by kebernet** [comment]
You know, to be honest, I have seen this a couple of times too, and I am not really sure what is causing it. :(  As far as I can tell, your NYT creds *should* be saved to your Google Play account, so even if you install on a new device, they should be auto-magically there. This seems to work about 80% of the time, and about 30% of the time  they get lost with an update. The problem is, it is so hard to duplicate the problem, I haven't been able to fix it.

"What causes the text of puzzles in the list to be red."

This was a bug. When I added the night mode (where I wanted the text red) I tripped over a bug in the build tools where the text and image color got out of sync and I screwed up trying to fix it. You shouldn't see that anymore.

**Comment by irontechmonkey** [comment]
Hello and thanks for your reply and explanation, particularly about the connection to Google.  I do enough with Firewalls and VPNs that this could have been an issue on my end as I sometimes test things with various Google services restricted. I saw the lost log-in only twice during that round of testing but never elsewhere, and, it has not happened since. App is looking good. Thanks again.

**Comment by irontechmonkey** [comment]
I think this issue had been addressed but since then the NY Times changed fomrat so this is moot a the app can no longer do times puzzles regardless if credentials.
